### ISSUE TITLE
Spawner_DraugrPile, BonePileSpawner, Spawner_GreydwarfNest

### ISSUE THREAD

**Issue by codore** [JereKuusela/valheim-expand_world_data#1]
Hello, I got an error when using your mod and I don't understand what the problem is, but because of this error the FPS drops a lot. The error occurs when a monster spawns from such spawners as: Spawner_DraugrPile, BonePileSpawner, Spawner_GreydwarfNest, maybe there are other spawners, but I didn't notice anymore.

MOD LIST:
DropThat! 2.3.11
ExpandWorldData 1.23
ExpandWorldEvents 1.6
ExpandWorldFactions 1.2
ExpandWorldPrefabs 1.6
ExpandWorldRivers 1.9
ExpandWorldSize 1.13
InfinityHammer 1.43
Jotunn 2.15.0
ServerDevcommands 1.66
SpawnerTweaks 1.23
SpawnThat! 1.2.8
StructureTweaks 1.27
WackysDatabase 2.1.6
WorldEditCommands 1.51

ERRORS:
----- 4x -----
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ExpandWorldData.Factions.FactionManager.TryGetFaction (System.String name, Character+Faction& faction) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
ExpandWorldData.Factions.TryParseBiome.Prefix (System.String value, Character+Faction& result, System.Boolean& __result) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
(wrapper dynamic-method) System.Enum.DMD(string,bool,Character/Faction&)
SpawnerTweaks.SpawnAreaPatches.ApplyChanges () (at <2836d20075324623a17a12c12fa3bca9>:0)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
--------------
[Warning: Unity Log] 12/11/2023 13:15:19: Local player destroyed
[Warning: Unity Log] 12/11/2023 13:15:19: Missing stat for guardian power: 
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ExpandWorldData.Factions.FactionManager.TryGetFaction (System.String name, Character+Faction& faction) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
ExpandWorldData.Factions.TryParseBiome.Prefix (System.String value, Character+Faction& result, System.Boolean& __result) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
(wrapper dynamic-method) System.Enum.DMD(string,bool,Character/Faction&)
SpawnerTweaks.SpawnAreaPatches.ApplyChanges () (at <2836d20075324623a17a12c12fa3bca9>:0)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
[Warning: Unity Log] 12/11/2023 13:15:40: Local player destroyed
[Warning: Unity Log] 12/11/2023 13:15:40: Missing stat for guardian power: 
----- 2x -----
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ExpandWorldData.Factions.FactionManager.TryGetFaction (System.String name, Character+Faction& faction) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
ExpandWorldData.Factions.TryParseBiome.Prefix (System.String value, Character+Faction& result, System.Boolean& __result) (at <27ce835fe69e4425bc73dd33dbcaefe2>:0)
(wrapper dynamic-method) System.Enum.DMD(string,bool,Character/Faction&)
SpawnerTweaks.SpawnAreaPatches.ApplyChanges () (at <2836d20075324623a17a12c12fa3bca9>:0)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
(wrapper dynamic-method) SpawnArea.DMD(SpawnArea)
--------------

**Comment by JereKuusela** [comment]
Fixed Spawner Tweaks v1.24
