### ISSUE TITLE
Dungeon Bug

### ISSUE THREAD

**Issue by IvanGarcia3131** [JereKuusela/valheim-expand_world_data#3]
[Info   : Unity Log] 12/15/2023 10:29:51: Loading dungeon

[Info   : Unity Log] 12/15/2023 10:29:51: Dungeon loaded with 0 rooms from old format in 0.9927 ms.

[Info   : Unity Log] 12/15/2023 10:29:51: Generating DG_Hildir_ForestCrypt, Seed: 103151843, Bounds diff: (-16.00, -176.00, 14.00) / (16.00, -44.00, 46.00)

[Info   : Unity Log] 12/15/2023 10:29:51: Available rooms:3

[Info   : Unity Log] 12/15/2023 10:29:51: To place:40

[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
DungeonGenerator.FindStartRoom () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
DungeonGenerator.PlaceStartRoom (ZoneSystem+SpawnMode mode) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
DungeonGenerator.GenerateDungeon (ZoneSystem+SpawnMode mode) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
DungeonGenerator.GenerateRooms (ZoneSystem+SpawnMode mode) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
DungeonGenerator.Generate (System.Int32 seed, ZoneSystem+SpawnMode mode) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) DungeonGenerator.DMD<DungeonGenerator::Generate>(DungeonGenerator,ZoneSystem/SpawnMode)
(wrapper dynamic-method) ZoneSystem.DMD<ZoneSystem::SpawnLocation>(ZoneSystem,ZoneSystem/ZoneLocation,int,UnityEngine.Vector3,UnityEngine.Quaternion,ZoneSystem/SpawnMode,System.Collections.Generic.List`1<UnityEngine.GameObject>)
(wrapper dynamic-method) ZoneSystem.DMD<ZoneSystem::PlaceLocations>(ZoneSystem,Vector2i,UnityEngine.Vector3,UnityEngine.Transform,Heightmap,System.Collections.Generic.List`1<ZoneSystem/ClearArea>,ZoneSystem/SpawnMode,System.Collections.Generic.List`1<UnityEngine.GameObject>)
ZoneSystem.SpawnZone (Vector2i zoneID, ZoneSystem+SpawnMode mode, UnityEngine.GameObject& root) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
ZoneSystem.CreateGhostZones (UnityEngine.Vector3 refPoint) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
ZoneSystem.Update () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

**Comment by JereKuusela** [comment]
Hildir update was released 4 months ago.

You can find the migration instructions from here: https://github.com/JereKuusela/valheim-expand_world_data/blob/231e54c20045c1daaf719824efa00c96684399fd/publish/README.md#migration-for-hildir-update
